#리팩터링 용 도커파일입니다. CPU 환경에서 리팩터링하고자 기존의 도커파일과 별개의 도커파일을 만들었습니다.

FROM python:3.11
# 작업 디렉토리 설정
WORKDIR /app

# pip 최신화
RUN pip install --upgrade pip

# 패키지 설치 (캐시 활용)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 소스 복사
COPY . .

# 포트 오픈
EXPOSE 8000

# 컨테이너 실행 시 기본 명령
CMD ["uvicorn", "app.server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
